##
# Copyright 2020 @dave-db.com
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
##

##
# * --------------------------------------------------------------------------------
# * Description:
# *        ToDo:
# * --------------------------------------------------------------------------------
##

route:
  receiver: 'netcool_messagebus_probe'
  group_by: [generatorURL, startsAt, endsAt, alertname, container_label_com_docker_swarm_task_name, container_label_com_docker_swarm_node_id]
  #group_by: [...]
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 10s

receivers:
  - name: 'netcool_messagebus_probe'
    webhook_configs:
    - url: 'http://10.16.8.61:8181/probe/dockerPreProd'
      send_resolved: true
      http_config:
       basic_auth:
        username: dockerswarm
        password: sm40!2019
